zhaohuabing/hugo-theme-cleanwhite

layouts/404.html, layouts/_default/baseof.html, layouts/_default/single.html, layouts/partials/comments.html, layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/header.html, layouts/partials/nav.html, layouts/partials/reward.html, layouts/partials/sidebar.html
There are two more little things that can be improved to make the template 'url portable'
relLangURL
and 
in nav.html
<a class="navbar-brand" href="{{ .Site.BaseURL }}/">{{ .Site.Title }}</a>
Thanks for making this!
belongs with #14
=> a few more little things to make the site url independent

.gitignore, layouts/_default/single.html
1. add .gitignore
2. format the doc
3. fix the page location issue
=> Fix Previous/Next Post locate wrong page #20

layouts/_default/baseof.html
Fix for issue #36 
I removed the duplicate nested <HEAD> tags that prevents document validation.
[Validation Test](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fzhaohuabing.com%2F#l252c34)
=> Fix for duplicate nested HEAD tags.

layouts/partials/nav.html, layouts/partials/sidebar.html
fix for issue #40
Added Alt tags to partials:
Nav.html
sidebar.html
This will allow the template to validate.
=> Fix Alt Tags so HTML will validate

layouts/partials/sidebar.html
{{ if .Site.Params.about_me }} was missing as well as the {{ end }}
=> Added site params for about_me

exampleSite/config.toml, layouts/partials/footer.html, layouts/partials/sidebar.html
I added some social buttons. For keybase and mastodon icons  Fontawesome 5 is needed. I'll try to implement it and make another PR.
=> Added icons for gitlab, git, stackoverflow, reddit, mastodon and keybase

layouts/_default/single.html, layouts/partials/post_list.html
If lastmod variabel is set in a content’s front matter it will displayed in list page and single page.
For more info about .Lastmod page variable see https://gohugo.io/variables/page/#page-variables
=> Add "Last Modified on" to list and single page.

exampleSite/config.toml, layouts/partials/head.html
Did some modifications to allow users to add their own js and css files. Files can be loaded from url or local files relative to /static folder.
=> add support for custom js and css

exampleSite/config.toml, layouts/partials/footer.html, layouts/partials/sidebar.html
Thx for the theme. While using this for me it was missing a social param XING.
=> Adds social param xing

layouts/partials/footer.html, layouts/partials/sidebar.html
This PR adds instagram and flickr to the socials in the sidebar.
=> Add instagram and flickr to socials

README.md
=> Fix link to config.toml

layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/sidebar.html
Adds support for a lot more brands.
=> Upgrade Fontawesome to version 5

layouts/partials/footer.html
编辑站点配置，在params段中添加如下的代码，支持markdown格式
```toml
[params]
icp = "[浙ICP备xxxxxxx号](http://www.beian.gov.cn)"
```
=> feature: 增加了icp配置

README.md, exampleSite/config.toml, layouts/partials/comments.html
=> Add twikoo comment

layouts/shortcodes/rawhtml.html
Implement `rawhtml` shortcode as described here: https://anaulin.org/blog/hugo-raw-html-shortcode/
=> Create rawhtml shortcode

layouts/_default/list.algolia.json
using "and" in order to confirm that only an article is neither a draft or a private post
=> bugfix: fixed a logical error in list.algolia.json

static/css/bootstrap.min.css
Formatted and edited in ` /static/css/bootstrap.min.css `
Added some new configuration on line 223-224, line 230-232 of ` /static/css/bootstrap.min.css `, new version. These modifications could make tables in articles more beautiful.
The followings are the changes.
=> Style modifications: Formatted the bootstrap.min.css, and edited some css configuration about tables

exampleSite/.gitignore, exampleSite/content/post/2017-11-08-istio-canary-release.md, exampleSite/content/post/2017-11-28-access-application-from-outside.md, exampleSite/content/post/2018-01-02-nginmesh-install.md, exampleSite/content/post/2018-02-03-authentication-and-authorization-of-microservice.md, exampleSite/content/post/2018-02-09-docker-without-sudo.md, exampleSite/content/post/2018-02-09-vim-tips.md, exampleSite/content/post/2018-03-13-use-docker-behind-http-proxy.md, exampleSite/content/post/2018-03-29-what-is-service-mesh-and-istio.md, exampleSite/content/post/2018-04-11-service-mesh-vs-api-gateway.md, exampleSite/content/post/2018-04-16-using-helm-to-deploy-to-kubernetes.md, exampleSite/content/post/2018-05-01-may-day-jiulonghu.md, exampleSite/content/post/2018-05-21-algolia-integration-with-jekyll.md, exampleSite/content/post/2018-05-22-user_authentication_authorization.md, exampleSite/content/post/2018-05-23-external_system_auth.md, exampleSite/content/post/2018-05-23-istio-auto-injection-with-webhook.md, exampleSite/content/post/2018-05-23-service_2_service_auth.md, exampleSite/content/post/2018-05-24-set_up_my_ubuntu_desktop.md, exampleSite/content/post/2018-06-02-istio08.md, exampleSite/content/post/2018-06-04-introducing-the-istio-v1alpha3-routing-api.md, exampleSite/hugo.toml
When previewing the example site with latest hugo version 0.144.0, several errors are thrown. This PR fixes these issues.
This PR closes #171.
=> Fix errors when previewing example site

README.md, exampleSite/content/post/2018-02-09-vim-tips.md, exampleSite/content/post/2018-05-23-service_2_service_auth.md, exampleSite/content/post/readme.md, exampleSite/hugo.toml, go.mod
Currently, when trying to preview the example site, an error is reported:
```
Error: command error: failed to load config: "/home/andreas/hugo-theme-cleanwhite/exampleSite/hugo.toml:120:16": unmarshal failed: toml: expected character ]
```
This PR fixes that issue and closes #181.
This PR brings multiple other improvements, see commit messages of the commits that form this PR.
=> Improvements

exampleSite/hugo.toml, layouts/partials/sidebar.html
That would be great to have a list of the last posts in the sidebar on the right in the front page.
=> feat: Add last posts in the sidebar
