zhaohuabing/hugo-theme-cleanwhite

exampleSite/config.toml
layouts/_default/single.html
layouts/partials/sidebar.html

Specifically, allow users to hide 'Friends' and 'Bookmarks' lists.
Update default template to reflect config.toml settings.
> Note: I'm less sure if updating the default is something you'd like to see happen or not, but I think it makes the overall page look cleaner.
_Empty headings in footer and sidebar_
_No headings where no content (this screenshot might not do the change justice, but it basically means that your website doesn't look actively incomplete if you don't have content in these sections)_

Add the option to hide recommendations

---

layouts/partials/head.html

@zhaohuabing 
I tried this issue #32 
I will report the verification results
Best regards
1,OGP thumbnail setting
2,OGP no setting
I made it possible to apply header_image when OGP is not set
3,OGP thumbnail setting and param setting  summary_large_image
post params
```---
title: OGP Image Large
description: 説明文
date: 2019-01-29T13:50:39.455Z
summary: summary_large_image
categories:
- SAMPLE
tags:
- SAMPLE
thumbnail: /img/uploads/tu-tu-322210-unsplash.jpg
```

add ogp params

---

layouts/partials/nav.html

fix for issue #34 
If your website baseurl is something like:
https://somedomain.com/somedirectory/
The Home url in the nav.html "/" resolves to the root directory (https://somedomain.com/) instead of https://somedomain.com/somedirectory/
Note: this may happen other places that I have just not happened upon.

Nav fix for non-root baseurl

---

layouts/partials/sidebar.html

Fix for issue #35 
If your website baseurl is something like:
https://somedomain.com/somedirectory/
Then you create a relative bookmark or friend link in your site it resolves to the root directory (https://somedomain.com/) instead of the correct path (https://somedomain.com/somedirectory/)
This can be fixed by updating the links to reflect the baseurl, but it can be resolved code.

Fix for relative links in friends and bookmarks

---

layouts/_default/single.html

.. with sitewide param in config.toml
since showtoc is by default true you how to add 'showtoc: false' to all your blog posts
if you dont want the toc beeing added.
keep the same behaviour as before but with the addition that you can now add a showtoc
as a sitewide param in config.toml to change the default behaviour (fallback value).
|Site Variable | Page Variable |  show toc? |
| ------------ | ------------- | ----------- | 
|    null      |    null       |    yes     |
|    null      |    false      |    no      |
|    null      |    true       |    yes     |
|    false     |    null       |    no      |
|    false     |    false      |    no      |
|    false     |    true       |    yes     |
|    true      |    null       |    true    |
|    true      |    false      |    no      | …

allow to override the default behaviour for showtoc

---

exampleSite/config.toml
layouts/partials/nav.html

I would rather not have all of the categories show up in my top bar. This adds a site param which omits the categories from showing up. Preserves default behaviour.

add site param 'omit_categories'

---

layouts/partials/footer.html

Newer versions of hugo crashed because `async` is now `js` keyword. See https://github.com/gohugoio/hugo/issues/8693

change func name to non js keyword

---

layouts/partials/footer.html
layouts/partials/sidebar.html

The wechat icon cannot be displayed after applying #95 due to the wrong class name in Font Awesome v5 is used. Change it from `fab fa-wechat` to `fab fa-weixin` (see the [reference](https://fontawesome.com/v5.15/icons/weixin?style=brands)).

fix: wrong class name for wechat fontawesome icon

---

exampleSite/config.toml
exampleSite/content/top/archive.md
layouts/_default/archive.html

Add a layout for the posts archiving page and enable the page in `exampleSite`.
Here is the preview when running the `exampleSite`:

feat: implement posts archiving page

---

layouts/shortcodes/notice.html

use code like this:
```
{{% notice tip %}}
Don't forget to make a first backup manually (just in case) an setup a periodical backup job on the long term 😉
{{% /notice %}}
```
to build such boxes:
The boxes feature layouts for the keywords `tip` (green), `info` (orange), `note` (blue) and `warning` (red)

Feature: Added nice little boxes for hints, warnings and tips

---

layouts/partials/post_list.html

The `post_list.html` is missing a whitespace between the "Posted by" and the author's name. Moreover, it's also missing an "on" keyword between the author's name and the post's date.
This whitespace and the "on" keyword are however present in the `single.html` page.
https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/7b64a06446db7aa1620e99186302a5ebe3f976cf/layouts/_default/single.html#L36
https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/7b64a06446db7aa1620e99186302a5ebe3f976cf/layouts/_default/single.html#L42
I'm proposing this change to make the layout consistent.
Thanks!

Update post_list.html to make the "Posted by" subtext more consistent

---

layouts/partials/head.html
layouts/shortcodes/rawhtml.html

Added a pipe " | " instead of a hyphen "-" delimiter to separate Title and SEO Title.

Change delimiter between Title and SEO Title in head.html

---

layouts/_default/single.html

Hi, I'm new to hugo theme, and I just published my first post with cleanwhite.
I noticed that the horizontal line and the block are still there even though the previous/next buttons do not need to be displayed, which is a bit odd to me.
Therefore, I added an if statement for the pager section, rendered as follows:
Just some edge cases, if it's ok for others then I'll close the PR. And thanks again for the nice theme!

Add if statement for pager section

---

README.md
exampleSite/content/post/readme.md

The API key given in the `config.toml` is visible to visitors of `/search/`.  As such it should not be the admin key as indicated but the search-only key.  According to Algolia:
> `Search-Only API Key`:
> This is the public API key to use in your frontend code. This key is only usable for search queries and sending data to the Insights API.
> `Admin API Key`
> This is the ADMIN API key. Please keep it secret and use it ONLY from your backend: this key is used to create, update and DELETE your indices. You can also use it to manage your API keys

Pages should be built with search only key.

---

layouts/partials/sidebar.html

Hello, thank you very much for the awesome Hugo theme!
I noticed the about link on the avatar is broken even for example site then I try to fix that. I am not sure that is the correct way to fix the issue. I would be grateful if you could advise me.
- If I click the avatar photo on the top page, it jumps to `top/about` and shows 404.
By fixing this line to `<a href="{{ "/about" | relLangURL }}">`(remove the `/top` path), this link works for me.
https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/ac188d67d1e82445b593142f6d20be4db19e26ed/layouts/partials/sidebar.html#L16

fix about link on avatar

---

exampleSite/config.toml
layouts/partials/footer.html

This commit adds a conditional flag for the attribution to @zhaohuabing in the footer partial.
This change is similar to #156 by @pengbin2015, but makes the behavior optional while keeping the default behavior as retaining the attribution and iframe to add the GitHub star.
Since this is a backwards-compatible feature add, I'd suggest this be versioned `2.1.0` per the [semantic versioning guidelines](https://semver.org/).
Thanks!

feat: add conditional for attribution to upstream repo

---

layouts/partials/comments.html
layouts/partials/head.html

Fixed bugs caused by removing a feature in the new version:
ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.GoogleAnalytics.ID instead.
---
ERROR deprecated: .Site.DisqusShortname  was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.Disqus.Shortname instead.

Fixed bugs caused by removing a feature in the new version

---

layouts/partials/footer.html

When the title is too long, the table of contents cannot fully display the title. By adding the 'title' attribute, the full title can be displayed when the mouse is placed on the table of contents.
The effect is shown in the figure below:

add 'title' attribute for catalog title

---

layouts/partials/sidebar.html

enable HTML rendering (e.g., `<br>` tags) for `sidebar_about_description`

enable HTML rendering for sidebar

---

exampleSite/hugo.toml
layouts/partials/nav.html

这也许是一处拼写错误。在文件themes/hugo-theme-cleanwhite/layouts/partials/nav.html中为{{ range .Site.Params.addtional_menus }}，我将单词addtional改为了additional。

The Spelling Error in a Word Was Corrected
